# this is a template. Copy to application-dev.yaml for development and change as needed
app:
  env: DEV
  port: 9000

database:
  filePath: /Users/me/code/.db

auth:
  secret: 'changeme-oig2pi2XaeJ1Oofechuu3AicdohCu6uLThitha6I'
  roles:
    - 'Admin'
    - 'Customer'