import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val com_github_johnrengelman_shadow_gradle_plugin: String =
            "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:_"

    const val com_google_cloud_tools_jib_gradle_plugin: String =
            "com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin:_"

    const val kotlin_result: String = "com.michael-bull.kotlin-result:kotlin-result:_"

    const val nimbus_jose_jwt: String = "com.nimbusds:nimbus-jose-jwt:_"

    const val hoplite_core: String = "com.sksamuel.hoplite:hoplite-core:_"

    const val hoplite_yaml: String = "com.sksamuel.hoplite:hoplite-yaml:_"

    const val com_squareup_sqldelight_gradle_plugin: String =
            "com.squareup.sqldelight:com.squareup.sqldelight.gradle.plugin:_"

    const val runtime_jvm: String = "com.squareup.sqldelight:runtime-jvm:_"

    const val sqlite_driver: String = "com.squareup.sqldelight:sqlite-driver:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val http4k_client_okhttp: String = "org.http4k:http4k-client-okhttp:_"

    const val http4k_core: String = "org.http4k:http4k-core:_"

    const val http4k_format_jackson: String = "org.http4k:http4k-format-jackson:_"

    const val http4k_server_undertow: String = "org.http4k:http4k-server-undertow:_"

    const val http4k_testing_kotest: String = "org.http4k:http4k-testing-kotest:_"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"

    const val jbcrypt: String = "org.mindrot:jbcrypt:_"
}
