name: Build app and push image to docker hub
on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Cache pnpm modules 📦
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Install and Build 🔧
        run: |
          pnpm install
          cd ./frontend
          pnpm run build

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: create-json ✍️
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'google-creds.json'
          json: ${{ secrets.GOOGLE_CREDS_JSON }}
          dir: 'secrets/'

      - name: Log in to Docker Hub 🔒
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rikuvan/bantamweight

      - name: Build and push Docker image 🖼️
        uses: docker/build-push-action@v2
        env:
          APP__ENV: ${{ secrets.APP__ENV }}
          AUTH__SECRET: ${{ secrets.AUTH__SECRET }}
          DATABASE__USER__LAST_NAME: ${{ secrets.DATABASE__USER__LAST_NAME }}
          DATABASE__USER__FIRST_NAME: ${{ secrets.DATABASE__USER__FIRST_NAME }}
          DATABASE__USER__EMAIL: ${{ secrets.DATABASE__USER__EMAIL }}
          DATABASE__USER__PASSWORD: ${{ secrets.DATABASE__USER__PASSWORD }}
          REPLICA_URL: ${{ secrets.REPLICA_URL }}
        with:
          context: .
          push: true
          tags: rikuvan/bantamweight:latest
